import "../styles/styles.scss"
import Head from "next/head"

import { AuthContextProvider } from "../contexts/AuthContext"

function MyApp({ Component, pageProps }) {
    return (
        <AuthContextProvider>
            <div className="width">
                <Head>
                    <title>Leboncoin petite annonce</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/Leboncoin_Icone.ico" />
                </Head>
                <Component {...pageProps} />
            </div>
        </AuthContextProvider>
    )
}

export default MyApp
