import "../styles/styles.scss"
import Head from "next/head"

function MyApp({ Component, pageProps }) {
    return (
        <div className="width">
            <Head>
                <title>Leboncoin petite annonce</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Leboncoin_Icone.ico" />
            </Head>
            <Component {...pageProps} />
        </div>
    )
}

export default MyApp
