import Head from "next/head"

import Header from "../components/header/header"

export default function Home() {
    return (
        <div>
            <Head>
                <title>Leboncoin petite annonce</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Leboncoin_Icone.ico" />
            </Head>

            <div>
                <Header />
            </div>
        </div>
    )
}
